require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'Litentry' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'LitentryTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #
  # Run pod install and build the app with xcode after uncomment this lile
  # use_flipper!({ 'Flipper' => '0.54.0', 'Flipper-RSocket' => '1.1', 'Flipper-Folly' => '2.3.0' })
  use_flipper!({ 'Flipper'=> '0.142.0' })

  post_install do |installer|
      react_native_post_install(installer)
      __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

target 'Litentry-tvOS' do
  # Pods for Litentry-tvOS

  target 'Litentry-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
