fastlane_require 'dotenv'

default_platform(:android)

platform :android do

  desc "Submit a new Beta Build"
  lane :beta do
    gradle(task: "clean")
    gradle(task: "bundleRelease")
    upload_to_play_store(track: "internal")
  end

end
