name: code-style-lint-tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  # Enable manual run
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: deploy
        run: |
          yarn 
          yarn codegen
          yarn validate
          yarn test
