name: code style & lint

on:
  push:
    branches: [ ci-test ]
  pull_request:
    branches: [ ci-test ]
  workflow_dispatch:


jobs:
  deploy:
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: deploy
        run: |
          yarn && yarn validate
