name: Slack Notification Android

on: 
  workflow_run:
    workflows: [Deploy to Play Store]
    types: 
      - completed
    branches: [develop]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: rn-app
          SLACK_COLOR: ${{ github.event.workflow_run.conclusion }}
          SLACK_TITLE: A new Android build is complete
          SLACK_USERNAME: RN-Bot
          SLACK_ICON_EMOJI: ${{ ':bell:' }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: 'GitHub Actions'
